Feature/create recipe service
YuryStruchkou/CookBookApi pull request #9
Opened 2019-07-30 11:29 UTC by YuryStruchkou

2019-09-19 08:21 UTC, mpobezhimova commented on ControllerTesting/Mocking/AccountMocking.cs
>                     || _users.Select(user => user.Email.ToLower()).Any(name => name == u.Email.ToLower());
можно использовать string.equals ignore case

2019-09-19 08:22 UTC, mpobezhimova commented on ControllerTesting/Mocking/AccountMocking.cs
> +            return new AccountController(MockedUserManager.Object, SetupMapper(), new JwtFactory("https://localhost:44342/", "gyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy", 60),
старайся такое выносить в config settings, или хотя бы в константы но лучше в сеттинги

2019-09-19 08:23 UTC, mpobezhimova commented on ControllerTesting/Mocking/AccountMocking.cs
> +            var token = "token";
"token" в константы

2019-09-19 08:24 UTC, mpobezhimova commented on ControllerTesting/Mocking/AccountMocking.cs
>              PasswordHash = "pass"
в config settings или константы

2019-09-19 08:27 UTC, mpobezhimova commented on ControllerTesting/Mocking/RecipeControllerMocking.cs
> +            null, null, null, null, null, null, null, null);
8 Null выглядит немного странно, может что-то подумать с дефолтными параметрами

2019-09-19 08:31 UTC, mpobezhimova commented on ControllerTesting/TestSuites/AccountTesting.cs
>              Assert.Equal("Incorrect username and/or password.", error.Errors[0]);
сравнивать текст ошибок в тестах не совсем хороший подход, т.к. текст может измениться, а логика нет

2019-09-19 08:32 UTC, mpobezhimova commented on ControllerTesting/TestSuites/AccountTesting.cs
> +            _mocker.MockedUserManager.Setup(m => m.FindByNameAsync("user1")).ReturnsAsync(new ApplicationUser
"user1" "token" в константы

2019-09-19 08:45 UTC, mpobezhimova requested changes
я бы поработала еще с именованием проектов для тестов, не совсем понятно что за Testing, ControllerTesting, какую логику ты там тестируешь, какой слой + по возможности разделяла UnitTests/IntegrationTests  
например можно указывать {project name}.UnitTests or {project name}.IntegrationTests

2019-09-24 19:35 UTC, YuryStruchkou commented
Поскольку пока я ждал ревью на этот ПР, я успел создать ещё несколько тестовых классов, то их именования мне будет проще поправить в будущем ПРе

2019-09-24 19:44 UTC, YuryStruchkou commented on ControllerTesting/Mocking/RecipeControllerMocking.cs
> +            null, null, null, null, null, null, null, null);
Здесь создаётся мок на применяемый в контроллере класс из дотнеткора. Этот класс прокидывается в контроллер через конструктор с помощью dependency injection и соответственно его создание остаётся за кадром. К сожалению, используемые методы этого класса не являются методами какого-либо интерфейса, поэтому приходится использовать конкретную реализацию и чтобы её замокать мне приходиться передавать параметры конструктора, а конструктор у этого класса лишь один и дефолтных параметров не имеет

2019-09-29 17:31 UTC, merged